In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv('cars.csv')
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

#### Check Duplicate Records

In [10]:
df_duplicate = df.duplicated().sum()
df_duplicate

np.int64(715)

#### Drop Duplicate Records

In [11]:
df = df.drop_duplicates()
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [12]:
df.shape

(11199, 16)

#### Check missing or null values

In [13]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### Drop missing or null values

In [14]:
df = df.dropna()
df.count()

Make                 7735
Model                7735
Year                 7735
Engine Fuel Type     7735
Engine HP            7735
Engine Cylinders     7735
Transmission Type    7735
Driven_Wheels        7735
Number of Doors      7735
Market Category      7735
Vehicle Size         7735
Vehicle Style        7735
highway MPG          7735
city mpg             7735
Popularity           7735
MSRP                 7735
dtype: int64

#### Show top 10 average MSRP (Price) per car brand (rounded figure)?

In [15]:
top_10_MSRP = df.groupby('Make')['MSRP'].mean().round().sort_values(ascending=False).head(10)
top_10_MSRP

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          237384.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

#### Show the average MSRP (price) per years (rounded figure)?

In [16]:
avg_MSRP_PerYear = df.groupby('Year')['MSRP'].mean().round().sort_index()
avg_MSRP_PerYear

Year
1990     2073.0
1991     2223.0
1992     2192.0
1993     2401.0
1994     2726.0
1995     3270.0
1996     3140.0
1997     4524.0
1998     4434.0
1999     3612.0
2000     3913.0
2001    73833.0
2002    55704.0
2003    68312.0
2004    55908.0
2005    53724.0
2006    39001.0
2007    41173.0
2008    80462.0
2009    59193.0
2010    60152.0
2011    65663.0
2012    71837.0
2013    55201.0
2014    71196.0
2015    52613.0
2016    52580.0
2017    45333.0
Name: MSRP, dtype: float64

#### Show average Engine HP (power) rounded figure and MPG (efficiency) rounded figure per year?

Hint: Average of (city mpg + highway MPG)

In [17]:
avg_hp_mpg_per_year = df.groupby('Year').agg({
    'Engine HP': 'mean',
    'city mpg': 'mean',
    'highway MPG': 'mean'
}).round()
avg_hp_mpg_per_year

      Engine HP  city mpg  highway MPG
Year
1990      154.0      18.0         24.0
1991      163.0      18.0         24.0
1992      155.0      19.0         25.0
1993      174.0      18.0         24.0
1994      167.0      18.0         25.0
1995      203.0      17.0         24.0
1996      201.0      18.0         24.0
1997      200.0      17.0         24.0
1998      224.0      17.0         24.0
1999      199.0      18.0         24.0
2000      202.0      18.0         24.0
2001      243.0      17.0         23.0
2002      244.0      15.0         22.0
2003      258.0      15.0         22.0
2004      260.0      16.0         23.0
2005      255.0      17.0         23.0
2006      248.0      17.0         24.0
2007      274.0      15.0         21.0
2008      298.0      16.0         22.0
2009      268.0      17.0         23.0
2010      269.0      17.0         24.0
2011      280.0      18.0         25.0
2012      293.0      19.0         26.0
2013      290.0      20.0         27.0
2014      311.0      20.0         26.0
2015      288.0      21.0         28.0
2016      290.0      21.0         28.0
2017      285.0      21.0         28.0

#### What percentage of cars are Compact, Midsize, or Large?

In [21]:
size_per = df['Vehicle Size'].value_counts(normalize=True)*100

In [22]:
Per_cars = size_per[['Compact', 'Midsize', 'Large']]
Per_cars.round(2)

Vehicle Size
Compact    36.81
Midsize    39.34
Large      23.85
Name: proportion, dtype: float64

#### Which vehicle styles are the most sold (most common) in the dataset?

In [23]:
most_common_styles = df['Vehicle Style'].value_counts().head(10)
most_common_styles

Vehicle Style
4dr SUV                2053
Sedan                  1801
Coupe                   922
Convertible             645
4dr Hatchback           639
2dr Hatchback           409
Wagon                   349
Crew Cab Pickup         334
Extended Cab Pickup     187
Regular Cab Pickup      176
Name: count, dtype: int64

#### Which car brands have the most vehicles priced at $40,000 or more and with a popularity score of at least 1000?

In [24]:
filtered_df = df[(df['MSRP'] >= 40000) & (df['Popularity'] >= 1000)]
filtered_df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
12,BMW,1 Series,2013,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,44400
15,BMW,1 Series,2013,premium unleaded (required),320.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,25,18,3916,48250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,BMW,Z4,2016,premium unleaded (required),240.0,4.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,34,22,3916,49700
11902,BMW,Z4,2016,premium unleaded (required),335.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,66350
11903,BMW,Z8,2001,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,128000
11904,BMW,Z8,2002,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,130000
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500