In [2]:
import pandas as pd
import sqlite3 as sql

In [3]:
conn = sql.connect('database.sqlite')
conn

In [4]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [5]:
pd.read_sql_query('select * from salaries',conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [6]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [7]:
sql_query('select * from salaries')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [9]:
q1 = """
    SELECT JobTitle,
           AVG(TotalPayBenefits) AS AvgTotalPayBenefits
    FROM Salaries
   WHERE JobTitle != 'Not Provided' AND JobTitle != 'Not provided'
    GROUP BY JobTitle
     ORDER BY AvgTotalPayBenefits DESC
"""
sql_query(q1)

                                            JobTitle  AvgTotalPayBenefits
0                           Chief Investment Officer        436224.360000
1                                    Chief of Police        411732.266667
2                             Chief, Fire Department        408865.326667
3     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY        399211.275000
4                         Gen Mgr, Public Trnsp Dept        380696.440000
...                                              ...                  ...
2153                           SPECIAL ASSISTANT XIV           673.800000
2154              BOARD/COMMISSION MEMBER, GROUP III           638.787879
2155                      BdComm Mbr, Grp2,M=$25/Mtg           475.047742
2156               BOARD/COMMISSION MEMBER, GROUP II           296.511628
2157         PUBLIC SAFETY COMMUNICATIONS TECHNICIAN           149.510000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [10]:
q2 = """select Jobtitle,OvertimePay from salaries
        where OvertimePay > 50000
        
       


"""
sql_query(q2)

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [12]:
q3 = ''' select Distinct EmployeeName as TotalEmployee
        From Salaries
        WHERE EmployeeName != 'Not Provided' 
        AND EmployeeName != 'Not provided'
'''
sql_query(q3)

             TotalEmployee
0           NATHANIEL FORD
1           ALBERT PARDINI
2        CHRISTOPHER CHONG
3          PATRICK GARDNER
4           DAVID SULLIVAN
...                    ...
110803   Afakasi O Afakasi
110804      Kenneth Mackey
110805      Mark W Mcclure
110806  Charlene D Mccully
110807           Joe Lopez

[110808 rows x 1 columns]

In [13]:
q3 = ''' select count(Distinct EmployeeName) as TotalEmployee
        From Salaries
        WHERE EmployeeName != 'Not Provided' 
        AND EmployeeName != 'Not provided'
'''
sql_query(q3)

   TotalEmployee
0         110808

#### **4.Show The Top 10 highest Paid Employees**

In [25]:
q4 = """
    SELECT *
    FROM Salaries
    ORDER BY TotalPayBenefits DESC
    LIMIT 10
"""
sql_query(q4)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,110532,David Shinn,Deputy Chief 3,129150.01,0.00,342802.63,38780.04,471952.64,510732.68,2014,,San Francisco,PT
2,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,,San Francisco,FT
3,110534,William J Coaker Jr.,Chief Investment Officer,257340.00,0.00,82313.70,96570.66,339653.70,436224.36,2014,,San Francisco,PT
4,72926,Gregory P Suhr,Chief of Police,319275.01,0.00,20007.06,86533.21,339282.07,425815.28,2013,,San Francisco,
5,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.00,23236.00,85431.39,336922.01,422353.40,2013,,San Francisco,
6,110535,Gregory P Suhr,Chief of Police,307450.04,0.00,19266.72,91302.46,326716.76,418019.22,2014,,San Francisco,FT
7,110536,Joanne M Hayes-White,"Chief, Fire Department",302068.00,0.00,24165.44,91201.66,326233.44,417435.10,2014,,San Francisco,FT
8,110537,Ellen G Moffatt,Asst Med Examiner,270222.04,6009.22,67956.20,71580.48,344187.46,415767.94,2014,,San Francisco,FT
9,36160,Gary Altenberg,"Lieutenant, Fire Suppression",128808.87,220909.48,13126.31,44430.12,362844.66,407274.78,2012,,San Francisco,

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [27]:
q5 = """
    SELECT *
    FROM Salaries
    ORDER BY TotalPayBenefits DESC
"""
sql_query(q5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,110532,David Shinn,Deputy Chief 3,129150.01,0,342802.63,38780.04,471952.64,510732.68,2014,,San Francisco,PT
2,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,,San Francisco,FT
3,110534,William J Coaker Jr.,Chief Investment Officer,257340,0,82313.7,96570.66,339653.70,436224.36,2014,,San Francisco,PT
4,72926,Gregory P Suhr,Chief of Police,319275.01,0,20007.06,86533.21,339282.07,425815.28,2013,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148649,110529,Timothy E Gibson,Police Officer 3,,0,0,-2.73,0.00,-2.73,2013,,San Francisco,
148650,110530,Mark E Laherty,Police Officer 3,,0,0,-8.2,0.00,-8.20,2013,,San Francisco,
148651,110531,David P Kucia,Police Officer 3,,0,0,-33.89,0.00,-33.89,2013,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT